import Link from "next/link";
import { Activity, ArrowRight, Clock3, CreditCard, DollarSign, Package, ShoppingBag, Sparkles, TrendingUp, WalletCards } from "lucide-react";
import { PageTitle } from "@/components/app-shell";
import { StatCard } from "@/components/stat-card";
import { formatCurrency, recentSales } from "@/lib/data";

const bars = [42, 55, 38, 68, 52, 79, 64, 88, 61, 72, 83, 67];
export default function DashboardPage() {
  return <>
    <PageTitle eyebrow="Visão geral" title="Seu negócio, em um só lugar" description="Acompanhe o movimento de hoje e tome decisões com mais clareza." action={<Link href="/sales" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#15231f] px-4 py-3 text-sm font-semibold text-white transition hover:bg-forest"><ShoppingBag size={17} />Abrir venda</Link>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Vendas hoje" value="R$ 1.248,50" change="12,8%" trend="up" icon={DollarSign} tone="dark" /><StatCard label="Pedidos realizados" value="38" change="8,4%" trend="up" icon={ShoppingBag} /><StatCard label="Ticket médio" value="R$ 32,85" change="3,2%" trend="up" icon={TrendingUp} /><StatCard label="Itens em estoque" value="209" change="4,1%" trend="down" icon={Package} /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_1fr]">
      <section className="rounded-2xl border border-[#e4e8df] bg-white p-5 shadow-soft sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-bold">Vendas da semana</h2><p className="mt-1 text-xs text-ink/45">Receita bruta por dia</p></div><button className="rounded-lg border border-[#e4e8df] px-3 py-2 text-xs font-semibold text-ink/60">Esta semana <span className="ml-1">⌄</span></button></div><div className="mt-8 flex h-56 items-end gap-2 sm:gap-4">{bars.map((height, i) => <div key={i} className="flex h-full flex-1 flex-col justify-end gap-2"><div className={`chart-bar relative rounded-t-lg ${i === 7 ? "bg-forest" : "bg-[#dcebd0]"}`} style={{ height: `${height}%`, animationDelay: `${i * 50}ms` }}>{i === 7 && <span className="absolute -top-7 left-1/2 -translate-x-1/2 rounded bg-ink px-2 py-1 text-[10px] font-bold text-white">R$ 312</span>}</div><span className="text-center text-[10px] text-ink/40">{["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"][i % 6]}</span></div>)}</div></section>
      <section className="rounded-2xl border border-[#e4e8df] bg-white p-5 shadow-soft sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">Resumo do caixa</h2><p className="mt-1 text-xs text-ink/45">Sessão atual</p></div><span className="flex items-center gap-1.5 rounded-full bg-[#eaf8ee] px-2.5 py-1 text-[10px] font-bold text-[#23804d]"><span className="h-1.5 w-1.5 rounded-full bg-[#42c98b]" />Aberto</span></div><div className="mt-6 rounded-xl bg-[#f5f8f1] p-4"><p className="text-xs text-ink/50">Saldo em caixa</p><p className="mt-1 text-3xl font-bold">R$ 2.486,50</p><div className="mt-4 flex items-center gap-1.5 text-xs font-semibold text-forest"><Activity size={14} />+ R$ 1.248,50 hoje</div></div><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="flex items-center gap-2 text-ink/55"><WalletCards size={15} />Abertura</span><b>R$ 1.238,00</b></div><div className="flex justify-between"><span className="flex items-center gap-2 text-ink/55"><CreditCard size={15} />Vendas no cartão</span><b>R$ 438,90</b></div><div className="flex justify-between"><span className="flex items-center gap-2 text-ink/55"><Clock3 size={15} />Aberto desde</span><b>08:02</b></div></div><Link href="/cash" className="mt-6 flex items-center justify-center gap-2 rounded-xl border border-[#dce5d6] py-3 text-xs font-bold text-forest hover:bg-[#f5f8f1]">Ver detalhes do caixa <ArrowRight size={14} /></Link></section>
    </div>
    <section className="mt-6 rounded-2xl border border-[#e4e8df] bg-white p-5 shadow-soft sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">Últimas vendas</h2><p className="mt-1 text-xs text-ink/45">Transações mais recentes</p></div><Link href="/sales" className="flex items-center gap-1 text-xs font-bold text-forest">Ver todas <ArrowRight size={14} /></Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b border-[#eef0eb] text-[10px] uppercase tracking-wider text-ink/40"><th className="pb-3 font-bold">Venda</th><th className="pb-3 font-bold">Horário</th><th className="pb-3 font-bold">Itens</th><th className="pb-3 font-bold">Pagamento</th><th className="pb-3 text-right font-bold">Total</th><th className="pb-3 text-right font-bold">Status</th></tr></thead><tbody>{recentSales.map((sale) => <tr key={sale.id} className="border-b border-[#f1f2ef] last:border-0"><td className="py-4 font-bold">{sale.id}<span className="ml-2 font-normal text-ink/45">{sale.customer}</span></td><td className="py-4 text-ink/55">{sale.time}</td><td className="py-4 text-ink/55">{sale.items} {sale.items === 1 ? "item" : "itens"}</td><td className="py-4 text-ink/55">{sale.method}</td><td className="py-4 text-right font-bold">{formatCurrency(sale.total)}</td><td className="py-4 text-right"><span className="rounded-full bg-[#eaf8ee] px-2.5 py-1 text-[10px] font-bold text-[#23804d]">{sale.status}</span></td></tr>)}</tbody></table></div></section>
    <div className="mt-6 flex items-center gap-3 rounded-2xl border border-[#dce8cb] bg-[#edf8df] p-4 text-sm text-ink sm:p-5"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-mint"><Sparkles size={18} /></div><p><b>Dica rápida:</b> produtos com estoque abaixo de 10 unidades aparecem destacados na sua lista de produtos.</p><Link href="/products" className="ml-auto hidden shrink-0 text-xs font-bold text-forest sm:block">Ver estoque <ArrowRight size={14} className="ml-1 inline" /></Link></div>
  </>;
}
