"use client";
import { useMemo, useState } from "react";
import { Archive, ChevronDown, Edit3, MoreHorizontal, Plus, Search, SlidersHorizontal, Trash2 } from "lucide-react";
import { PageTitle } from "@/components/app-shell";
import { formatCurrency, products } from "@/lib/data";

export default function ProductsPage() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("Todas");
  const [showForm, setShowForm] = useState(false);
  const filtered = useMemo(() => products.filter((p) => (category === "Todas" || p.category === category) && `${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase())), [query, category]);
  return <><PageTitle eyebrow="Catálogo" title="Produtos" description="Gerencie seus produtos, preços e níveis de estoque." action={<button onClick={() => setShowForm(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#15231f] px-4 py-3 text-sm font-semibold text-white hover:bg-forest"><Plus size={17} />Novo produto</button>} />
    <div className="mb-5 flex flex-col gap-3 rounded-2xl border border-[#e4e8df] bg-white p-3 shadow-soft sm:flex-row"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink/35" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nome ou código..." className="w-full rounded-xl bg-[#f7f8f3] py-3 pl-10 pr-3 text-sm outline-none ring-forest/20 transition focus:ring-2" /></div><div className="flex gap-2"><div className="relative"><select value={category} onChange={(e) => setCategory(e.target.value)} className="h-full appearance-none rounded-xl border border-[#e4e8df] bg-white py-3 pl-3 pr-9 text-xs font-semibold outline-none"><option>Todas</option><option>Bebidas</option><option>Lanches</option><option>Doces</option></select><ChevronDown size={14} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-ink/45" /></div><button className="grid w-12 place-items-center rounded-xl border border-[#e4e8df] text-ink/55 hover:bg-[#f7f8f3]" aria-label="Filtros"><SlidersHorizontal size={17} /></button></div></div>
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-[#e4e8df] bg-white p-4"><p className="text-xs text-ink/50">Total de produtos</p><p className="mt-1 text-2xl font-bold">{products.length}</p></div><div className="rounded-2xl border border-[#e4e8df] bg-white p-4"><p className="text-xs text-ink/50">Valor em estoque</p><p className="mt-1 text-2xl font-bold">{formatCurrency(products.reduce((sum, p) => sum + p.price * p.stock, 0))}</p></div><div className="rounded-2xl border border-[#f5d7c9] bg-[#fff8f4] p-4"><p className="text-xs text-[#a95c3f]">Estoque baixo</p><p className="mt-1 text-2xl font-bold text-[#a95c3f]">{products.filter((p) => p.stock < 10).length} <span className="text-sm font-medium">produtos</span></p></div></div>
    <div className="mt-6 overflow-hidden rounded-2xl border border-[#e4e8df] bg-white shadow-soft"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-[#fafbf8]"><tr className="border-b border-[#eef0eb] text-[10px] uppercase tracking-wider text-ink/40"><th className="px-5 py-4 font-bold">Produto</th><th className="py-4 font-bold">Categoria</th><th className="py-4 font-bold">Preço</th><th className="py-4 font-bold">Estoque</th><th className="py-4 font-bold">Status</th><th className="py-4 pr-5 text-right font-bold">Ações</th></tr></thead><tbody>{filtered.map((product) => <tr key={product.id} className="border-b border-[#f1f2ef] last:border-0 hover:bg-[#fbfcfa]"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl text-sm font-bold text-ink" style={{ background: product.accent }}>{product.name.slice(0, 1)}</div><div><p className="font-bold">{product.name}</p><p className="mt-0.5 text-xs text-ink/40">{product.sku}</p></div></div></td><td className="py-4 text-ink/55">{product.category}</td><td className="py-4 font-semibold">{formatCurrency(product.price)}</td><td className="py-4"><span className={product.stock < 10 ? "font-bold text-[#c76542]" : "font-medium"}>{product.stock} un.</span>{product.stock < 10 && <span className="ml-2 rounded-full bg-[#fff0e9] px-2 py-1 text-[10px] font-bold text-[#c76542]">Repor</span>}</td><td className="py-4"><span className="rounded-full bg-[#eaf8ee] px-2.5 py-1 text-[10px] font-bold text-[#23804d]">Ativo</span></td><td className="py-4 pr-5 text-right"><button className="rounded-lg p-2 text-ink/40 hover:bg-[#f1f4ed] hover:text-ink" aria-label={`Editar ${product.name}`}><Edit3 size={16} /></button><button className="rounded-lg p-2 text-ink/40 hover:bg-[#f1f4ed] hover:text-ink" aria-label="Mais ações"><MoreHorizontal size={16} /></button></td></tr>)}</tbody></table></div>{filtered.length === 0 && <div className="p-10 text-center text-sm text-ink/50">Nenhum produto encontrado.</div>}<div className="flex items-center justify-between border-t border-[#eef0eb] px-5 py-4 text-xs text-ink/45"><span>Mostrando {filtered.length} de {products.length} produtos</span><span className="flex items-center gap-1"><Archive size={14} /> Catálogo local</span></div></div>
    {showForm && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-5"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Novo produto</h2><button onClick={() => setShowForm(false)} className="text-ink/40">✕</button></div><p className="mt-1 text-sm text-ink/50">Adicione um item ao catálogo para começar a vender.</p><div className="mt-5 space-y-3"><input placeholder="Nome do produto" className="w-full rounded-xl border border-[#e4e8df] px-3 py-3 text-sm outline-none focus:border-forest" /><div className="grid grid-cols-2 gap-3"><input placeholder="Preço (R$)" className="w-full rounded-xl border border-[#e4e8df] px-3 py-3 text-sm outline-none focus:border-forest" /><input placeholder="Estoque" className="w-full rounded-xl border border-[#e4e8df] px-3 py-3 text-sm outline-none focus:border-forest" /></div></div><button onClick={() => setShowForm(false)} className="mt-5 w-full rounded-xl bg-[#15231f] py-3 text-sm font-bold text-white">Salvar produto</button></div></div>}
  </>;
}
